sudo: false
language: c
compiler:
  - gcc
  - clang
script:
  - git submodule update --init
  - cmake -B build -S .
  - cd build
  - make test
addons:
  apt:
    packages:
      - libcjson-dev
os:
  - linux
